
  CREATE OR REPLACE FORCE VIEW "RECHERCHE"."V_DIRECTEUR_THESE" ("RAS_ID", "PERS_ID", "C_STRUCTURE", "ASS_ID", "RAS_RANG", "RAS_COMMENTAIRE", "RAS_D_OUVERTURE", "RAS_D_FERMETURE", "D_CREATION", "D_MODIFICATION", "RAS_QUOTITE", "PERS_ID_CREATION", "PERS_ID_MODIFICATION", "RAS_PRINCIPALE", "PERS_NOMPTR", "PERS_LC", "ID_THESE") AS 
  Select DISTINCT GRA."RAS_ID",GRA."PERS_ID",GRA."C_STRUCTURE",GRA."ASS_ID",GRA."RAS_RANG",GRA."RAS_COMMENTAIRE",GRA."RAS_D_OUVERTURE",GRA."RAS_D_FERMETURE",GRA."D_CREATION",GRA."D_MODIFICATION",GRA."RAS_QUOTITE",GRA."PERS_ID_CREATION",GRA."PERS_ID_MODIFICATION",GRA."RAS_PRINCIPALE", GP.PERS_NOMPTR, GP.PERS_LC, RDT.ID_THESE
              from 
              GRHUM.PERSONNE GP, 
              GRHUM.ASSOCIATION GA, 
              GRHUM.REPART_ASSOCIATION GRA, 
              ACCORDS.CONTRAT_PARTENAIRE ACP, 
              ACCORDS.CONTRAT AC,
              RECHERCHE.DOCTORANT_THESE RDT                
              WHERE  
              GA.ASS_CODE ='D_DIR_THESE' 
              AND GA.ASS_ID = GRA.ASS_ID 
              AND GRA.PERS_ID = GP.PERS_ID 
              AND GRA.C_STRUCTURE = AC.CON_GROUPE_PARTENAIRE 
              AND RDT.CON_ORDRE = AC.CON_ORDRE 
              AND ACP.CON_ORDRE = RDT.CON_ORDRE ;