
  CREATE OR REPLACE FORCE VIEW "RECHERCHE"."V_ECOLE_DOCTORALE_THESE" ("ID_DOCTORANT", "ID_THESE", "FD.ETAB_CODE", "FD.FDIP_CODE", "LL_STRUCTURE", "FDIP_MENTION") AS 
  SELECT DISTINCT D.ID_DOCTORANT, T.ID_THESE, FD.ETAB_CODE, FD.FDIP_CODE, I.LL_STRUCTURE, FD.FDIP_MENTION
    FROM RECHERCHE.DOCTORANT D
    LEFT OUTER JOIN RECHERCHE.DOCTORANT_THESE T ON D.ID_DOCTORANT = T.ID_DOCTORANT
    INNER JOIN ACCORDS.CONTRAT C ON T.CON_ORDRE = C.CON_ORDRE
    INNER JOIN ACCORDS.CONTRAT_PARTENAIRE CP ON C.CON_ORDRE = CP.CON_ORDRE
    INNER JOIN GRHUM.STRUCTURE_ULR I ON I.PERS_ID = CP.PERS_ID
    INNER JOIN GRHUM.REPART_ASSOCIATION RA ON RA.PERS_ID = CP.PERS_ID AND RA.C_STRUCTURE = C.CON_GROUPE_PARTENAIRE
    INNER JOIN GRHUM.ASSOCIATION A ON A.ASS_ID = RA.ASS_ID
    INNER JOIN SCOLARITE.SCOL_FORMATION_DIPLOME FD ON I.LC_STRUCTURE = FD.FDIP_CODE
    WHERE D.ID_DOCTORANT >= 1 /*iddoctorant*/
    AND ASS_CODE = 'D_ED_R' ;