
  CREATE OR REPLACE FORCE VIEW "RECHERCHE"."V_ETABLISSEMENT_COTUTELLE" ("ID_THESE", "ID_DOCTORANT", "CON_ORDRE", "ASS_ID", "ASS_CODE", "ASS_LIBELLE", "PERS_LIBELLE") AS 
  select distinct RDT.ID_THESE, RDT.ID_DOCTORANT, RDT.CON_ORDRE, GRA.ASS_ID, GA.ASS_CODE, GA.ASS_LIBELLE, P.PERS_LIBELLE
from RECHERCHE.DOCTORANT_THESE RDT, ACCORDS.CONTRAT_PARTENAIRE ACP,  GRHUM.PERSONNE P, GRHUM.REPART_ASSOCIATION GRA, GRHUM.ASSOCIATION GA 
WHERE RDT.CON_ORDRE = ACP.CON_ORDRE and ACP.PERS_ID = P.PERS_ID and P.PERS_ID = GRA.PERS_ID AND GRA.ASS_ID= GA.ASS_ID AND GA.ASS_CODE='D_COT_ETAB' ;